"""btrbk configuration and systemd-unit generation."""

from __future__ import annotations

from wslarc.config import Config
from wslarc.generators.invocation import systemd_command
from wslarc.generators.systemd import path_to_unit_name


def generate_config(config: Config) -> str:
    lines = [
        "# /etc/btrbk/btrbk.conf",
        "# Generated by wslarc",
        "",
        "# Global settings",
        "transaction_log         /var/log/btrbk.log",
        "lockfile                /var/lock/btrbk.lock",
        "timestamp_format        long",
        "",
        "# Snapshot preserve policy",
        f"snapshot_preserve_min   {config.btrbk.preserve_min}",
        f"snapshot_preserve       {config.btrbk.preserve}",
        "",
        f"volume {config.mount.base}",
        f"  snapshot_dir {config.btrbk.snapshot_dir}",
        "",
        "  # Configured A-class backup targets",
    ]
    for subvol in config.subvolumes.backup:
        lines.extend([f"  subvolume {subvol}", f"    snapshot_name {subvol.lstrip('@')}", ""])
    lines.append("  # Configured snapshot-only subvolumes")
    for subvol, snapshot in config.subvolumes.snapshot_only.items():
        lines.extend([f"  subvolume {subvol}", f"    snapshot_name {snapshot.snapshot_name}", ""])
    lines.extend(
        [
            "# B-class nested subvolumes are automatically excluded",
            "# C-class transfer subvolumes are not snapshotted",
        ]
    )
    return "\n".join(lines)


def generate_service(config: Config, config_path: str) -> str:
    base_unit = f"{path_to_unit_name(config.mount.base)}.mount"
    return (
        "[Unit]\n"
        "Description=btrbk Btrfs Snapshot Backup\n"
        f"Requires={base_unit}\n"
        f"After={base_unit}\n\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"ExecStart={systemd_command(config_path)} snapshot run\n"
        "Nice=19\n"
        "IOSchedulingClass=idle\n"
    )


def generate_timer(schedule: str) -> str:
    return (
        "[Unit]\n"
        "Description=btrbk Daily Snapshot Timer\n\n"
        "[Timer]\n"
        f"OnCalendar={schedule}\n"
        "RandomizedDelaySec=30min\n"
        "Persistent=true\n\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )
