"""APT and Pacman package-hook generation."""

from __future__ import annotations

from collections import deque
from collections.abc import Callable

from wslarc.config import Config, Distribution
from wslarc.generators.systemd import path_to_unit_name
from wslarc.utils.packages import (
    debian_query_depends,
    debian_query_version,
    pacman_query_depends,
    pacman_query_version,
)

SYSTEMD_PACKAGES = ("systemd", "systemd-libs", "systemd-sysvcompat")
DEBIAN_SYSTEMD_PACKAGES = ("systemd", "systemd-sysv", "libsystemd0")
PACMAN_HOOK_PATH = "/etc/pacman.d/hooks/sync-systemd-ext4.hook"
APT_HOOK_PATH = "/etc/apt/apt.conf.d/99wslarc-sync-systemd"
ARCH_PENDING_PACKAGES = "/run/wslarc/arch-pending-packages"
APT_PENDING_PACKAGES = "/run/wslarc/apt-pending-packages"
APT_SYNC_STATE = "/run/wslarc/apt-sync-state"


def generate_pacman_hook(targets: list[str]) -> str:
    lines = [
        "[Trigger]",
        "Operation = Upgrade",
        "Type = Package",
        *(f"Target = {target}" for target in targets),
        "",
        "[Action]",
        "Description = Syncing systemd to ext4...",
        "When = PostTransaction",
        "NeedsTargets",
        "Exec = /usr/local/bin/wslarc hook-sync-systemd",
        "",
    ]
    return "\n".join(lines)


def generate_apt_hook() -> str:
    return """// Generated by wslarc.
// Keep the host systemd package set in sync with the ext4 WSL root.
DPkg::Pre-Install-Pkgs {
  "/usr/local/bin/wslarc hook-sync-systemd --apt-pre || true";
};
DPkg::Post-Invoke {
  "/usr/local/bin/wslarc hook-sync-systemd --apt-post || true";
};
"""


def generate_package_hook(distribution: Distribution, targets: list[str]) -> tuple[str, str]:
    if distribution is Distribution.ARCH:
        return PACMAN_HOOK_PATH, generate_pacman_hook(targets)
    return APT_HOOK_PATH, generate_apt_hook()


def collect_recursive_targets(
    roots: tuple[str, ...],
    deps_for: Callable[[str], list[str]],
    is_installed: Callable[[str], bool],
) -> list[str]:
    queue: deque[str] = deque(roots)
    seen: set[str] = set()
    installed_roots: set[str] = set()
    while queue:
        package = queue.popleft()
        if not is_installed(package) or package in seen:
            continue
        seen.add(package)
        if package in roots:
            installed_roots.add(package)
        queue.extend(dependency for dependency in deps_for(package) if dependency not in seen)
    return sorted(seen) if installed_roots else []


def collect_hook_targets(distribution: Distribution) -> list[str]:
    if distribution is Distribution.ARCH:
        return collect_recursive_targets(
            SYSTEMD_PACKAGES,
            pacman_query_depends,
            lambda package: pacman_query_version(package) is not None,
        )
    return collect_recursive_targets(
        DEBIAN_SYSTEMD_PACKAGES,
        debian_query_depends,
        lambda package: debian_query_version(package) is not None,
    )


def generate_ext4_mount(config: Config, uuid: str) -> str:
    mount_point = config.ext4_sync.mount_point
    return (
        "[Unit]\n"
        "Description=Mount ext4 root for sync\n\n"
        "[Mount]\n"
        f"What=UUID={uuid}\n"
        f"Where={mount_point}\n"
        "Type=ext4\n"
        "Options=defaults\n\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def ext4_mount_unit_filename(config: Config) -> str:
    return f"{path_to_unit_name(config.ext4_sync.mount_point)}.mount"
